# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<END
#!/bin/bash

# Create pgdg.list
echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list > /dev/null

# Import repository key
wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -

# Update the package lists
sudo apt-get update -y

# Install postgresql
sudo DEBIAN_FRONTEND=noninteractive apt-get install postgresql-8.4 -y
END

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.vm.hostname = "test"
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
  config.vm.network "forwarded_port", guest: 5432, host: 6432, auto_correct: true
  config.vm.define "testing"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
     vb.cpus=2
  end
  config.vm.provision "shell", inline: $script
end
