---
# tasks file for php-fpm
- name: Install required system packages
  apt:
    update_cache: true

- name: Install php-fpm packages
  apt:
    name: 
      - php7.4
      - php7.4-fpm
      - php7.4-cli
      - php7.4-json
      - php7.4-pdo
      - php7.4-mysql
      - php7.4-zip
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-curl
      - php7.4-xml
      - php-pear
      - php7.4-bcmath
    state: present

- name: Start and enable service
  service:
    name: php7.4-fpm
    state: started
    enabled: yes

- name: Create scripts directory
  file:
    path: /var/www/html
    state: directory

- name: Create PHP info page
  template:
    src: index.php.j2
    dest: /var/www/html/index.php

- name: Configure php pool conf
  lineinfile:
    path: /etc/php/7.4/fpm/pool.d/www.conf
    search_string: 'listen = '
    line: 'listen = 0.0.0.0:9000'
  notify: Reload php
