---
- hosts: web
  gather_facts: true
  become: true

  tasks:
    - name: Install required system packages
      apt:
        update_cache: true
      tags:
      - update

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      notify:
      - Start Nginx

    - name: Edit index.html
      template:
        src: /home/user/.ansible/template/index.html.j2
        dest: /var/www/html/index.html
      notify:
      - Reload nginx

  handlers:
    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
